env:
  node: true
  browser: true
  commonjs: true
  es2021: true
extends:
 # - eslint:recommended
 # - plugin:react/recommended
  - airbnb-base
  - plugin:jest/recommended

parserOptions:
  ecmaVersion: latest
plugins:
#  - react
  - jest

rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  no-console: 0
  import/extensions: # FIXME: remove when rule will be adjusted for new nodejs version
    - error
    - ignorePackages
    - js: always
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
